name: Run Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-every-minute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-minute job
        run: |
          echo "This job runs every minute."
